import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    common: {
      save: 'Save Changes',
      cancel: 'Cancel',
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      actions: 'Actions',
      status: 'Status',
      loading: 'Loading...',
      success: 'Success',
      error: 'Error',
      active: 'Active',
      resolved: 'Resolved',
      submit: 'Submit'
    },
    nav: {
      dashboard: 'Dashboard',
      farms: 'Farms',
      visitors: 'Visitors',
      biosecurity: 'Biosecurity',
      alerts: 'Alerts',
      reports: 'Reports',
      settings: 'Settings',
      disease_scanner: 'Disease Scanner',
      logout: 'Logout',
      light_mode: 'Light Mode',
      dark_mode: 'Dark Mode',
      portal_title: 'FarmGuard',
      portal_subtitle: 'Biosecurity Portal'
    },
    auth: {
      welcome_back: 'Welcome back',
      signin_subtitle: 'Sign in to your FarmGuard account',
      create_account: 'Create your account',
      signup_subtitle: 'Start managing your farm biosecurity',
      email: 'Email Address',
      password: 'Password',
      confirm_password: 'Confirm Password',
      repeat_password: 'Repeat password',
      full_name: 'Full Name',
      full_name_placeholder: 'John Smith',
      email_placeholder: 'you@farm.com',
      password_placeholder: '••••••••',
      password_hint: 'Min. 6 characters',
      signin_btn: 'Sign In',
      signing_in: 'Signing in...',
      signup_btn: 'Create Account',
      signing_up: 'Creating account...',
      no_account: "Don't have an account?",
      have_account: 'Already have an account?',
      login_link: 'Sign In',
      register_link: 'Create account',
      welcome_toast: 'Welcome back!',
      register_toast: 'Account created! Welcome to FarmGuard.',
      error_login: 'Login failed. Please try again.',
      error_register: 'Registration failed.',
      validate_name: 'Full name is required',
      validate_email: 'Email is required',
      validate_email_format: 'Invalid email format',
      validate_password: 'Password is required',
      validate_password_len: 'Password must be at least 6 characters',
      validate_confirm: 'Passwords do not match'
    },
    dashboard: {
      title: 'Dashboard',
      greeting_morning: 'Good morning',
      greeting_afternoon: 'Good afternoon',
      greeting_evening: 'Good evening',
      overview_subtitle: "Here's your farm overview.",
      view_farms: 'View Farms',
      new_alert: 'New Alert',
      total_farms: 'Total Farms',
      healthy_count: 'healthy',
      active_alerts: 'Active Alerts',
      critical_count: 'critical',
      pending_visitors: 'Pending Visitors',
      awaiting_approval: 'Awaiting approval',
      avg_compliance: 'Avg. Compliance',
      biosecurity_score: 'Biosecurity score',
      activity_trend: '7-Day Activity Trend',
      live_indicator: 'Live',
      visitors: 'Visitors',
      alerts: 'Alerts',
      no_alerts: 'No active alerts',
      no_visitors: 'No pending visitors'
    },
    scanner: {
      title: 'AI Disease Scanner',
      subtitle: 'Analyze pictures of your farm animals dynamically using advanced neural vision algorithms to detect disease outbreaks early.',
      banner_title: 'AI Disease Scanner & Monitor',
      banner_desc: 'Capture or upload clear close-ups of sick animals or crop anomalies to run real-time automated pathogen assessments.',
      source_selection: 'Select Input Source',
      camera_mode: 'Real-time Camera',
      upload_mode: 'Image Upload',
      allow_camera: 'Please allow camera permissions to start scanning.',
      camera_error: 'Could not access camera. Please use file upload.',
      start_camera: 'Start Camera Feed',
      stop_camera: 'Stop Camera Feed',
      capture_btn: 'Capture & Analyze',
      upload_prompt: 'Drag & drop your farm animal image here, or',
      browse_files: 'browse files',
      file_selected: 'Image loaded successfully.',
      scan_now: 'Analyze Image',
      scanning_progress: 'Simulated AI Analysis...',
      scan_log_1: 'Detecting physical anomalies...',
      scan_log_2: 'Analyzing lesion pattern structures...',
      scan_log_3: 'Verifying body thermal signatures...',
      scan_log_4: 'Cross-referencing viral pathogens...',
      diagnostic_report: 'AI Diagnostic Report',
      confidence: 'Confidence Rate',
      pathogen: 'Diagnosed Pathogen',
      severity: 'Severity Level',
      symptoms: 'Detected Symptoms',
      recommendations: 'Quarantine Procedures',
      action_required: 'Required Actions',
      outbreak_persist: 'File Outbreak Alert',
      outbreak_submitting: 'Filing Alert...',
      select_farm: 'Select Affected Farm',
      affected_count: 'Number of Affected Animals',
      log_success: 'Outbreak alert logged successfully and recorded in database!',
      log_error: 'Failed to record outbreak alert. Please try again.',
      alert_title: 'AI Diagnostic: {disease}',
      alert_description: 'An AI disease scan identified {disease} with {confidence}% confidence. Immediate inspection recommended.',
      severity_critical: 'Critical',
      severity_high: 'High',
      severity_medium: 'Medium',
      severity_low: 'Low',
      no_farms_error: 'You must create a farm before submitting a disease outbreak alert.'
    },
    farms: {
      title: 'Farm Management',
      managed_count: '{count} farm{plural} managed',
      add_farm: 'Add Farm',
      search_placeholder: 'Search farms...',
      all_types: 'All Types',
      all_status: 'All Status',
      no_farms_title: 'No farms found',
      no_farms_desc: 'Add your first farm to get started.',
      banner_title: 'My Farm Lands',
      banner_desc: 'Easily manage, view and update your farm lands, biosecurity status and alert tracking.',
      farm_name: 'Farm Name *',
      farm_type: 'Farm Type *',
      capacity: 'Capacity *',
      location: 'Location *',
      description: 'Description',
      adding: 'Adding...',
      saving: 'Saving...',
      save_changes: 'Save Changes',
      cancel: 'Cancel',
      add_new_title: 'Add New Farm',
      edit_title: 'Edit Farm',
      delete_title: 'Delete Farm',
      delete_msg: 'Are you sure you want to delete "{name}"? This will remove all associated data.',
      delete_btn: 'Delete Farm',
      type_pig: '🐷 Pig Farm',
      type_poultry: '🐔 Poultry Farm',
      type_mixed: '🏡 Mixed Farm',
      view_details: 'View Details →'
    },
    visitors: {
      title: 'Visitor Logs',
      banner_title: 'Farm Visitors Log',
      banner_desc: 'Keep track of all visitors entering your farms to maintain strict biosecurity protocols.',
      add_visitor: 'Log Visitor',
      search_placeholder: 'Search visitors...',
      all_farms: 'All Farms',
      all_statuses: 'All Statuses',
      no_visitors_title: 'No visitor logs found',
      no_visitors_desc: 'Log a visitor to track entry compliance.',
      log_visitor_title: 'Log Farm Visitor',
      edit_visitor_title: 'Edit Visitor Log',
      visitor_name: 'Visitor Name *',
      farm: 'Target Farm *',
      purpose: 'Purpose of Visit *',
      contact: 'Contact Number *',
      company: 'Company / Organization *',
      vehicle: 'Vehicle Number *',
      temp_check: 'Temperature Check passed (°C) *',
      disinfection: 'Full Disinfection completed *',
      ppe_worn: 'PPE & boots worn *',
      risk_score: 'Risk Assessment Score',
      high_risk_warning: '⚠️ High Biosecurity Risk! Ensure proper disinfection before entry.',
      approve_btn: 'Approve Entry',
      reject_btn: 'Deny Entry',
      submitting: 'Submitting...',
      allowed: 'Allowed',
      denied: 'Denied',
      pending: 'Pending',
      status_approved: 'Approved',
      status_denied: 'Denied',
      status_pending: 'Pending'
    },
    alerts_page: {
      title: 'Real-time Alerts',
      banner_title: 'Biosecurity Warnings & Threats',
      banner_desc: 'Receive instant alerts regarding active outbreaks, temperature thresholds, and compliance violations near your area.',
      create_alert: 'Create New Alert',
      search_placeholder: 'Search alerts...',
      all_types: 'All Types',
      all_severities: 'All Severities',
      no_alerts_title: 'No alerts found',
      no_alerts_desc: 'No active threat alerts in your system.',
      create_alert_title: 'Create Threat Alert',
      alert_title_label: 'Alert Title *',
      alert_type: 'Alert Type *',
      severity: 'Severity *',
      affected_farm: 'Affected Farm *',
      description: 'Detailed Description *',
      submitting: 'Filing...',
      file_alert_btn: 'File Threat Alert',
      type_outbreak: 'Disease Outbreak',
      type_temp: 'Temperature Threshold',
      type_biosecurity: 'Biosecurity Breach',
      type_other: 'Other Threat',
      sev_critical: 'Critical',
      sev_high: 'High',
      sev_medium: 'Medium',
      sev_low: 'Low',
      resolve_btn: 'Resolve Alert',
      delete_btn: 'Delete Alert',
      delete_title: 'Delete Alert',
      delete_msg: 'Are you sure you want to delete this alert?'
    },
    biosecurity: {
      title: 'Biosecurity Protocols',
      banner_title: 'Farm Biosecurity Protocol Check',
      banner_desc: 'Audit your farm biosecurity standard operating procedures and track real-time compliance.',
      score_card: 'Overall Compliance Score',
      score_desc: 'Based on visitor screenings, disinfection audits, and active outbreak levels.',
      checklist_title: 'Core Compliance Checklist',
      check_disinfection: 'Daily Vehicle Disinfection Arch',
      check_ppe: 'Farmer/Staff PPE Gear Verification',
      check_boundary: 'Secure Fencing & Boundary Control',
      check_waste: 'Proper Mortalities Disposal Pit',
      check_feed: 'Clean Feed & Water Chlorination',
      risk_analysis: 'Dynamic Risk Analysis',
      risk_msg: 'All systems operational. Risk is currently low.',
      risk_high_msg: 'Warning: Risk is elevated due to pending visitor evaluations and active regional threat markers.',
      run_audit: 'Run Audit Scan',
      total_checks: 'Total Checks',
      completed: 'Completed',
      pending: 'Pending',
      rate: 'Completion Rate',
      all_farms: 'All Farms',
      all_cats: 'All Categories',
      all_status: 'All Status',
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      no_checklists: 'No checklists found',
      no_checklists_desc: 'Add biosecurity protocol checklists for your farms.',
      add_protocol: 'Add Protocol',
      upload_photo: 'Upload Verification Photo',
      upload_desc: 'Upload a photo to verify: {name}',
      click_to_upload: 'Click to upload image',
      uploading: 'Uploading...',
      farm: 'Farm *',
      protocol_name: 'Protocol Name *',
      category: 'Category',
      due_date: 'Due Date',
      notes: 'Notes',
      select_farm: 'Select farm...',
      cancel: 'Cancel'
    },
    reports: {
      title: 'Compliance Reports',
      banner_title: 'Analytics & Compliance Reports',
      banner_desc: 'Export official biosecurity logs and analyze historical trends of your farm lands.',
      total_visitors: 'Total Visitors Logged',
      total_alerts: 'Active Threat Alerts',
      avg_score: 'Avg. Biosecurity Score',
      recent_activity: 'Recent Logged Activities',
      export_pdf: 'Export PDF Report',
      export_csv: 'Export CSV Data',
      filter_date: 'Date Range',
      analytics_title: 'Reports & Analytics',
      generated_at: 'Generated: {date}',
      print_report: 'Print Report',
      compliance_report: 'Compliance Report',
      visitor_analytics: 'Visitor Analytics',
      disease_incidents: 'Disease Incidents',
      all_farms: 'All Farms',
      generate: 'Generate',
      click_generate: 'Click "Generate" to load the report',
      overall_biosecurity_score: 'Overall Biosecurity Score',
      farms_fully_compliant: 'Farms Fully Compliant',
      farms_need_attention: 'Farms Need Attention',
      farm_compliance_rates: 'Farm Compliance Rates',
      farm_by_farm_breakdown: 'Farm-by-Farm Breakdown',
      visitor_status_distribution: 'Visitor Status Distribution',
      top_visit_purposes: 'Top Visit Purposes',
      visits_by_farm: 'Visits by Farm',
      alert_severity_distribution: 'Alert Severity Distribution',
      incidents_by_farm: 'Incidents by Farm',
      recent_incidents: 'Recent Incidents',
      total_incidents: 'Total Incidents',
      critical_alerts: 'Critical Alerts',
      active_alerts_count: 'Active Alerts',
      animals_affected: 'Animals Affected',
      table_farm: 'Farm',
      table_type: 'Type',
      table_checks: 'Checks Done',
      table_compliance: 'Compliance',
      table_status: 'Status',
      table_title: 'Title',
      table_severity: 'Severity',
      table_affected: 'Affected',
      table_date: 'Date'
    },
    settings_page: {
      title: 'System Settings',
      banner_title: 'User Profile & Preferences',
      banner_desc: 'Configure your credentials, dark mode transitions, global translation triggers, and high-contrast settings.',
      profile_info: 'Profile Information',
      name: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      avatar: 'Profile Picture',
      upload_avatar: 'Change Avatar',
      language: 'Global Translation Language',
      theme: 'Theme Mode',
      farmer_mode: 'Farmer Simplified Mode',
      farmer_mode_desc: 'Displays big visual banners, simplified buttons, larger typographic lines, and intuitive navigation.',
      save_btn: 'Save Settings',
      saving: 'Saving...',
      tab_profile: 'Profile',
      tab_security: 'Security',
      tab_notifications: 'Notifications',
      tab_users: 'User Management',
      personal_info: 'Personal Information',
      role: 'Role',
      email_hint: 'Email cannot be changed.',
      change_password: 'Change Password',
      current_password: 'Current Password',
      new_password: 'New Password',
      confirm_new_password: 'Confirm New Password',
      update_password: 'Update Password',
      updating: 'Updating...',
      session_info: 'Session Info',
      logged_in_as: 'Logged in as',
      session_expires: 'Session expires',
      session_expiry_value: '24 hours from login',
      notification_preferences: 'Notification Preferences',
      pref_critical: 'Critical Disease Alerts',
      pref_critical_desc: 'Receive immediate notifications for critical disease outbreaks',
      pref_visitors: 'New Visitor Requests',
      pref_visitors_desc: 'Get notified when visitors request farm access',
      pref_reports: 'Report Generation Complete',
      pref_reports_desc: 'Notify when scheduled reports are ready for download',
      pref_digest: 'Weekly Digest',
      pref_digest_desc: 'Weekly summary of farm biosecurity status',
      save_preferences: 'Save Preferences',
      user_management: 'User Management',
      table_user: 'User',
      table_email: 'Email',
      table_role: 'Role',
      table_joined: 'Joined'
    }
  },
  ta: {
    common: {
      save: 'மாற்றங்களைச் சேமி',
      cancel: 'ரத்து செய்',
      add: 'சேர்',
      edit: 'தொகு',
      delete: 'நீக்கு',
      actions: 'நடவடிக்கைகள்',
      status: 'நிலை',
      loading: 'ஏற்றப்படுகிறது...',
      success: 'வெற்றி',
      error: 'பிழை',
      active: 'செயலில் உள்ளது',
      resolved: 'தீர்க்கப்பட்டது',
      submit: 'சமர்ப்பி'
    },
    nav: {
      dashboard: 'டாஷ்போர்டு',
      farms: 'பண்ணைகள்',
      visitors: 'பார்வையாளர்கள்',
      biosecurity: 'உயிரியல் பாதுகாப்பு',
      alerts: 'எச்சரிக்கைகள்',
      reports: 'அறிக்கைகள்',
      settings: 'அமைப்புகள்',
      disease_scanner: 'நோய் ஸ்கேனர்',
      logout: 'வெளியேறு',
      light_mode: 'பகல் முறை',
      dark_mode: 'இரவு முறை',
      portal_title: 'பார்ம்கார்டு',
      portal_subtitle: 'உயிரியல் பாதுகாப்பு போர்டல்'
    },
    auth: {
      welcome_back: 'மீண்டும் வருக',
      signin_subtitle: 'உங்கள் பார்ம்கார்டு கணக்கில் உள்நுழையவும்',
      create_account: 'உங்கள் கணக்கை உருவாக்கவும்',
      signup_subtitle: 'பண்ணை உயிரியல் பாதுகாப்பை நிர்வகிக்கத் தொடங்குங்கள்',
      email: 'மின்னஞ்சல் முகவரி',
      password: 'கடவுச்சொல்',
      confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      repeat_password: 'கடவுச்சொல்லை மீண்டும் தட்டச்சு செய்யவும்',
      full_name: 'முழு பெயர்',
      full_name_placeholder: 'ஜான் ஸ்மித்',
      email_placeholder: 'you@farm.com',
      password_placeholder: '••••••••',
      password_hint: 'குறைந்தது 6 எழுத்துக்கள்',
      signin_btn: 'உள்நுழைக',
      signing_in: 'உள்நுழைகிறது...',
      signup_btn: 'கணக்கை உருவாக்கு',
      signing_up: 'கணக்கு உருவாக்கப்படுகிறது...',
      no_account: 'கணக்கு இல்லையா?',
      have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
      login_link: 'உள்நுழைக',
      register_link: 'கணக்கை உருவாக்கு',
      welcome_toast: 'மீண்டும் வரவேற்கிறோம்!',
      register_toast: 'கணக்கு உருவாக்கப்பட்டது! பார்ம்கார்டுக்கு உங்களை வரவேற்கிறோம்.',
      error_login: 'உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
      error_register: 'பதிவு தோல்வியடைந்தது.',
      validate_name: 'முழு பெயர் தேவை',
      validate_email: 'மின்னஞ்சல் தேவை',
      validate_email_format: 'தவறான மின்னஞ்சல் வடிவம்',
      validate_password: 'கடவுச்சொல் தேவை',
      validate_password_len: 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்',
      validate_confirm: 'கடவுச்சொற்கள் பொருந்தவில்லை'
    },
    dashboard: {
      title: 'டாஷ்போர்டு',
      greeting_morning: 'காலை வணக்கம்',
      greeting_afternoon: 'மதிய வணக்கம்',
      greeting_evening: 'மாலை வணக்கம்',
      overview_subtitle: 'உங்கள் பண்ணையின் தற்போதைய நிலவரம்.',
      view_farms: 'பண்ணைகளை பார்க்க',
      new_alert: 'புதிய எச்சரிக்கை',
      total_farms: 'மொத்த பண்ணைகள்',
      healthy_count: 'ஆரோக்கியமானது',
      active_alerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
      critical_count: 'அபாயகரமானது',
      pending_visitors: 'காத்திருக்கும் பார்வையாளர்கள்',
      awaiting_approval: 'ஒப்புதலுக்காகக் காத்திருக்கிறது',
      avg_compliance: 'சராசரி இணக்கம்',
      biosecurity_score: 'உயிரியல் பாதுகாப்பு மதிப்பெண்',
      activity_trend: '7-நாள் செயல்பாட்டு போக்கு',
      live_indicator: 'நேரடி',
      visitors: 'பார்வையாளர்கள்',
      alerts: 'எச்சரிக்கைகள்',
      no_alerts: 'செயலில் உள்ள எச்சரிக்கைகள் இல்லை',
      no_visitors: 'காத்திருக்கும் பார்வையாளர்கள் யாரும் இல்லை'
    },
    scanner: {
      title: 'AI நோய் ஸ்கேனர்',
      subtitle: 'பண்ணை விலங்குகளின் புகைப்படங்களை மேம்பட்ட நியூரல் விஷன் அல்காரிதம் மூலம் பகுப்பாய்வு செய்து நோய்களை முன்கூட்டியே கண்டறியவும்.',
      banner_title: 'AI நோய் கண்டறிதல் & கண்காணிப்பு',
      banner_desc: 'விலங்குகளின் புண்கள் அல்லது பயிர் முரண்பாடுகளின் தெளிவான படங்களை எடுத்து நிகழ்நேர நோய் கண்டறிதலைத் தொடங்கவும்.',
      source_selection: 'உள்ளீட்டு மூலத்தைத் தேர்ந்தெடுக்கவும்',
      camera_mode: 'நிகழ்நேர கேமரா',
      upload_mode: 'புகைப்படப் பதிவேற்றம்',
      allow_camera: 'ஸ்கேன் செய்ய கேமரா அனுமதிகளை வழங்கவும்.',
      camera_error: 'கேமராவை அணுக முடியவில்லை. கோப்பு பதிவேற்றத்தைப் பயன்படுத்தவும்.',
      start_camera: 'கேமரா ஊட்டத்தைத் தொடங்கு',
      stop_camera: 'கேமரா ஊட்டத்தை நிறுத்து',
      capture_btn: 'படம் எடுத்து பகுப்பாய்வு செய்',
      upload_prompt: 'உங்கள் பண்ணை விலங்கு படங்களை இங்கே இழுத்து விடவும், அல்லது',
      browse_files: 'கோப்புகளைத் தேடவும்',
      file_selected: 'படம் வெற்றிகரமாக ஏற்றப்பட்டது.',
      scan_now: 'படத்தை பகுப்பாய்வு செய்',
      scanning_progress: 'செயற்கை நுண்ணறிவு பகுப்பாய்வு...',
      scan_log_1: 'உடல் முரண்பாடுகளைக் கண்டறிகிறது...',
      scan_log_2: 'புண் மாதிரி அமைப்புகளை பகுப்பாய்வு செய்கிறது...',
      scan_log_3: 'உடல் வெப்பநிலையைச் சரிபார்க்கிறது...',
      scan_log_4: 'வைரஸ் நோய்க்கிருமிகளை ஒப்பிடுகிறது...',
      diagnostic_report: 'AI நோய் கண்டறிதல் அறிக்கை',
      confidence: 'நம்பகத்தன்மை விகிதம்',
      pathogen: 'கண்டறியப்பட்ட நோய்',
      severity: 'தீவிரத்தன்மை நிலை',
      symptoms: 'கண்டறியப்பட்ட அறிகுறிகள்',
      recommendations: 'தனிமைப்படுத்தல் நடைமுறைகள்',
      action_required: 'தேவைப்படும் நடவடிக்கைகள்',
      outbreak_persist: 'நோய் எச்சரிக்கையை சமர்ப்பி',
      outbreak_submitting: 'எச்சரிக்கை சமர்ப்பிக்கப்படுகிறது...',
      select_farm: 'பாதிக்கப்பட்ட பண்ணையைத் தேர்ந்தெடுக்கவும்',
      affected_count: 'பாதிக்கப்பட்ட விலங்குகளின் எண்ணிக்கை',
      log_success: 'நோய் எச்சரிக்கை வெற்றிகரமாக தரவுத்தளத்தில் பதிவு செய்யப்பட்டது!',
      log_error: 'நோய் எச்சரிக்கையைப் பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      alert_title: 'AI நோய் கண்டறிதல்: {disease}',
      alert_description: 'AI நோய் ஸ்கேன் மூலம் {disease} பாதிப்பு {confidence}% நம்பகத்தன்மையுடன் கண்டறியப்பட்டுள்ளது. உடனடி ஆய்வு பரிந்துரைக்கப்படுகிறது.',
      severity_critical: 'மிகவும் அபாயகரமானது',
      severity_high: 'அதிகம்',
      severity_medium: 'மத்திமம்',
      severity_low: 'குறைவு',
      no_farms_error: 'நோய் எச்சரிக்கையைச் சமர்ப்பிக்கும் முன் நீங்கள் ஒரு பண்ணையை உருவாக்க வேண்டும்.'
    },
    farms: {
      title: 'பண்ணை மேலாண்மை',
      managed_count: '{count} பண்ணைகள் நிர்வகிக்கப்படுகின்றன',
      add_farm: 'பண்ணையைச் சேர்',
      search_placeholder: 'பண்ணைகளைத் தேடு...',
      all_types: 'அனைத்து வகைகள்',
      all_status: 'அனைத்து நிலைகள்',
      no_farms_title: 'பண்ணைகள் எதுவும் இல்லை',
      no_farms_desc: 'தொடங்குவதற்கு உங்கள் முதல் பண்ணையைச் சேர்க்கவும்.',
      banner_title: 'என் பண்ணை நிலங்கள்',
      banner_desc: 'உங்கள் பண்ணை நிலங்கள், உயிரியல் பாதுகாப்பு நிலை மற்றும் எச்சரிக்கைகளை எளிதாக நிர்வகியுங்கள்.',
      farm_name: 'பண்ணை பெயர் *',
      farm_type: 'பண்ணை வகை *',
      capacity: 'கொள்ளளவு *',
      location: 'இருப்பிடம் *',
      description: 'விளக்கம்',
      adding: 'சேர்க்கப்படுகிறது...',
      saving: 'சேமிக்கப்படுகிறது...',
      save_changes: 'மாற்றங்களைச் சேமி',
      cancel: 'ரத்து செய்',
      add_new_title: 'புதிய பண்ணையைச் சேர்',
      edit_title: 'பண்ணையைத் தொகு',
      delete_title: 'பண்ணையை நீக்கு',
      delete_msg: 'நிச்சயமாக நீங்கள் "{name}" பண்ணையை நீக்க விரும்புகிறீர்களா? இது அனைத்து தரவையும் நீக்கிவிடும்.',
      delete_btn: 'பண்ணையை நீக்கு',
      type_pig: '🐷 பன்றிப் பண்ணை',
      type_poultry: '🐔 கோழிப் பண்ணை',
      type_mixed: '🏡 கலப்புப் பண்ணை',
      view_details: 'விவரங்களைப் பார்க்க →'
    },
    visitors: {
      title: 'பார்வையாளர் பதிவுகள்',
      banner_title: 'பண்ணை பார்வையாளர்கள் பதிவு',
      banner_desc: 'கடுமையான உயிரியல் பாதுகாப்பு நெறிமுறைகளைப் பராமரிக்க உங்கள் பண்ணைகளுக்குள் வரும் அனைத்து பார்வையாளர்களைக் கண்காணிக்கவும்.',
      add_visitor: 'பார்வையாளரைப் பதிவு செய்',
      search_placeholder: 'பார்வையாளர்களைத் தேடு...',
      all_farms: 'அனைத்து பண்ணைகள்',
      all_statuses: 'அனைத்து நிலைகள்',
      no_visitors_title: 'பார்வையாளர் பதிவுகள் இல்லை',
      no_visitors_desc: 'வருகை இணக்கத்தைக் கண்காணிக்க ஒரு பார்வையாளரை பதிவு செய்யவும்.',
      log_visitor_title: 'பார்வையாளர் வருகையைப் பதிவு செய்',
      edit_visitor_title: 'வருகை பதிவைத் தொகு',
      visitor_name: 'பார்வையாளர் பெயர் *',
      farm: 'பண்ணை *',
      purpose: 'வருகை நோக்கம் *',
      contact: 'தொடர்பு எண் *',
      company: 'நிறுவனம் / அமைப்பு *',
      vehicle: 'வாகன எண் *',
      temp_check: 'வெப்பநிலை பரிசோதனை முடிந்தது (°C) *',
      disinfection: 'முழு கிருமிநாசினி தெளிப்பு முடிந்தது *',
      ppe_worn: 'பாதுகாப்பு உடைகள் மற்றும் காலணிகள் அணியப்பட்டுள்ளன *',
      risk_score: 'ஆபத்து மதிப்பீட்டு மதிப்பெண்',
      high_risk_warning: '⚠️ அதிக உயிரியல் ஆபத்து! நுழைவதற்கு முன் சரியான கிருமிநாசினி தெளிப்பை உறுதிப்படுத்தவும்.',
      approve_btn: 'நுழைவை அனுமதி',
      reject_btn: 'நுழைவை மறு',
      submitting: 'சமர்ப்பிக்கப்படுகிறது...',
      allowed: 'அனுமதிக்கப்பட்டது',
      denied: 'மறுக்கப்பட்டது',
      pending: 'காத்திருக்கிறது',
      status_approved: 'அனுமதிக்கப்பட்டது',
      status_denied: 'மறுக்கப்பட்டது',
      status_pending: 'காத்திருக்கிறது'
    },
    alerts_page: {
      title: 'நிகழ்நேர எச்சரிக்கைகள்',
      banner_title: 'உயிரியல் பாதுகாப்பு எச்சரிக்கைகள் & ஆபத்துகள்',
      banner_desc: 'உங்கள் பகுதிக்கு அருகிலுள்ள நோய்ப்பரவல், வெப்பநிலை மாற்றங்கள் மற்றும் பாதுகாப்பு மீறல்கள் குறித்த உடனடி எச்சரிக்கைகளைப் பெறுங்கள்.',
      create_alert: 'புதிய எச்சரிக்கையை உருவாக்கு',
      search_placeholder: 'எச்சரிக்கைகளைத் தேடு...',
      all_types: 'அனைத்து வகைகள்',
      all_severities: 'அனைத்து தீவிர நிலைகள்',
      no_alerts_title: 'எச்சரிக்கைகள் எதுவும் இல்லை',
      no_alerts_desc: 'உங்கள் கணினியில் செயலில் உள்ள ஆபத்து எச்சரிக்கைகள் எதுவும் இல்லை.',
      create_alert_title: 'பாதுகாப்பு எச்சரிக்கையை உருவாக்கு',
      alert_title_label: 'எச்சரிக்கை தலைப்பு *',
      alert_type: 'எச்சரிக்கை வகை *',
      severity: 'தீவிரத்தன்மை *',
      affected_farm: 'பாதிக்கப்பட்ட பண்ணை *',
      description: 'விரிவான விளக்கம் *',
      submitting: 'சமர்ப்பிக்கப்படுகிறது...',
      file_alert_btn: 'எச்சரிக்கையைச் சமர்ப்பி',
      type_outbreak: 'நோய் பரவல்',
      type_temp: 'வெப்பநிலை வரம்பு மீறல்',
      type_biosecurity: 'பாதுகாப்பு விதிமீறல்',
      type_other: 'இதர அச்சுறுத்தல்கள்',
      sev_critical: 'மிகவும் அபாயகரமானது',
      sev_high: 'அதிகம்',
      sev_medium: 'மத்திமம்',
      sev_low: 'குறைவு',
      resolve_btn: 'எச்சரிக்கையைத் தீர்க்கவும்',
      delete_btn: 'எச்சரிக்கையை நீக்கு',
      delete_title: 'எச்சரிக்கையை நீக்கு',
      delete_msg: 'நிச்சயமாக இந்த எச்சரிக்கையை நீக்க விரும்புகிறீர்களா?'
    },
    biosecurity: {
      title: 'உயிரியல் பாதுகாப்பு விதிகள்',
      banner_title: 'உயிரியல் பாதுகாப்பு விதிகள் சரிபார்ப்பு',
      banner_desc: 'உங்கள் பண்ணை உயிரியல் பாதுகாப்பு விதிகளை தணிக்கை செய்து இணக்கத்தைக் கண்காணிக்கவும்.',
      score_card: 'ஒட்டுமொ้த்த இணக்க மதிப்பெண்',
      score_desc: 'பார்வையாளர் பரிசோதனை, கிருமிநாசினி தணிக்கை மற்றும் செயலில் உள்ள நோய்ப்பரவல்களின் அடிப்படையில் கணக்கிடப்படுகிறது.',
      checklist_title: 'முக்கிய இணக்க சரிபார்ப்புப் பட்டியல்',
      check_disinfection: 'தினசரி வாகன கிருமிநாசினி தெளிப்பு',
      check_ppe: 'விவசாயி/ஊழியர்கள் பாதுகாப்பு உடை சரிபார்ப்பு',
      check_boundary: 'பாதுகாப்பான வேலி மற்றும் எல்லைக் கட்டுப்பாடு',
      check_waste: 'முறையான கழிவு அகற்றல் குழி',
      check_feed: 'சுத்தமான தீவனம் மற்றும் நீர் குளோரினேற்றம்',
      risk_analysis: 'நிகழ்நேர ஆபத்து பகுப்பாய்வு',
      risk_msg: 'அனைத்து அமைப்புகளும் சரியாக உள்ளன. ஆபத்து குறைவாக உள்ளது.',
      risk_high_msg: 'எச்சரிக்கை: பார்வையாளர் மதிப்பீடுகள் மற்றும் பிராந்திய அச்சுறுத்தல்கள் காரணமாக ஆபத்து அதிகமாக உள்ளது.',
      run_audit: 'தணிக்கை செய்',
      total_checks: 'மொத்த சோதனைகள்',
      completed: 'முடிந்தது',
      pending: 'காத்திருக்கிறது',
      rate: 'நிறைவு விகிதம்',
      all_farms: 'அனைத்து பண்ணைகள்',
      all_cats: 'அனைத்து பிரிவுகள்',
      all_status: 'அனைத்து நிலைகள்',
      daily: 'தினசரி',
      weekly: 'வாராந்திர',
      monthly: 'மாதாந்திர',
      no_checklists: 'சரிபார்ப்புப் பட்டியல்கள் எதுவும் இல்லை',
      no_checklists_desc: 'உங்கள் பண்ணைகளுக்கான உயிரியல் பாதுகாப்பு நெறிமுறை சரிபார்ப்புப் பட்டியல்களைச் சேர்க்கவும்.',
      add_protocol: 'நெறிமுறையைச் சேர்',
      upload_photo: 'சரிபார்ப்பு புகைப்படத்தைப் பதிவேற்றவும்',
      upload_desc: 'சரிபார்க்க புகைப்படத்தைப் பதிவேற்றவும்: {name}',
      click_to_upload: 'படத்தைப் பதிவேற்ற கிளிக் செய்யவும்',
      uploading: 'பதிவேற்றப்படுகிறது...',
      farm: 'பண்ணை *',
      protocol_name: 'நெறிமுறை பெயர் *',
      category: 'பிரிவு',
      due_date: 'கெடு தேதி',
      notes: 'குறிப்புகள்',
      select_farm: 'பண்ணையைத் தேர்ந்தெடுக்கவும்...',
      cancel: 'ரத்து செய்'
    },
    reports: {
      title: 'இணக்க அறிக்கைகள்',
      banner_title: 'பகுப்பாய்வு மற்றும் இணக்க அறிக்கைகள்',
      banner_desc: 'உயிரியல் பாதுகாப்பு பதிவுகளை ஏற்றுமதி செய்து உங்கள் பண்ணை நிலங்களின் வரலாற்றுப் போக்குகளை பகுப்பாய்வு செய்யவும்.',
      total_visitors: 'பதிவு செய்யப்பட்ட பார்வையாளர்கள்',
      total_alerts: 'செயலில் உள்ள அச்சுறுத்தல்கள்',
      avg_score: 'சராசரி பாதுகாப்பு மதிப்பெண்',
      recent_activity: 'சமீபத்திய நடவடிக்கைகள்',
      export_pdf: 'PDF ஆக ஏற்றுமதி செய்',
      export_csv: 'CSV ஆக ஏற்றுமதி செய்',
      filter_date: 'தேதி வரம்பு',
      analytics_title: 'அறிக்கைகள் மற்றும் பகுப்பாய்வு',
      generated_at: 'உருவாக்கப்பட்டது: {date}',
      print_report: 'அறிக்கையை அச்சிடு',
      compliance_report: 'இணக்க அறிக்கை',
      visitor_analytics: 'பார்வையாளர் பகுப்பாய்வு',
      disease_incidents: 'நோய் சம்பவங்கள்',
      all_farms: 'அனைத்து பண்ணைகள்',
      generate: 'உருவாக்கு',
      click_generate: 'அறிக்கையை ஏற்ற "உருவாக்கு" பொத்தானை அழுத்தவும்',
      overall_biosecurity_score: 'ஒட்டுமொத்த உயிரியல் பாதுகாப்பு மதிப்பெண்',
      farms_fully_compliant: 'முழுமையான இணக்க பண்ணைகள்',
      farms_need_attention: 'கவனம் தேவைப்படும் பண்ணைகள்',
      farm_compliance_rates: 'பண்ணை இணக்க விகிதங்கள்',
      farm_by_farm_breakdown: 'பண்ணை வாரியான விவரம்',
      visitor_status_distribution: 'பார்வையாளர் நிலை விநியோகம்',
      top_visit_purposes: 'முக்கிய வருகை நோக்கங்கள்',
      visits_by_farm: 'பண்ணை வாரியாக வருகைகள்',
      alert_severity_distribution: 'எச்சரிக்கை தீவிர நிலை விநியோகம்',
      incidents_by_farm: 'பண்ணை வாரியாக சம்பவங்கள்',
      recent_incidents: 'சமீபத்திய சம்பவங்கள்',
      total_incidents: 'மொத்த சம்பவங்கள்',
      critical_alerts: 'அபாயகரமான எச்சரிக்கைகள்',
      active_alerts_count: 'செயலில் உள்ள எச்சரிக்கைகள்',
      animals_affected: 'பாதிக்கப்பட்ட விலங்குகள்',
      table_farm: 'பண்ணை',
      table_type: 'வகை',
      table_checks: 'சோதனைகள்',
      table_compliance: 'இணக்கம்',
      table_status: 'நிலை',
      table_title: 'தலைப்பு',
      table_severity: 'தீவிரத்தன்மை',
      table_affected: 'பாதிப்பு',
      table_date: 'தேதி'
    },
    settings_page: {
      title: 'அமைப்பு அமைப்புகள்',
      banner_title: 'பயனர் சுயவிவரம் மற்றும் விருப்பங்கள்',
      banner_desc: 'உங்கள் நற்சான்றிதழ்கள், தீம் மாற்றங்கள், மொழி அமைப்புகள் மற்றும் எளிய விவசாயி பயன்முறையை உள்ளமைக்கவும்.',
      profile_info: 'சுயவிவரத் தகவல்',
      name: 'முழு பெயர்',
      email: 'மின்னஞ்சல் முகவரி',
      phone: 'தொலைபேசி எண்',
      avatar: 'சுயவிவரப் படம்',
      upload_avatar: 'சுயவிவரப் படத்தை மாற்று',
      language: 'மொழி தேர்வு',
      theme: 'தீம் பயன்முறை',
      farmer_mode: 'விவசாயி எளிமையான பயன்முறை',
      farmer_mode_desc: 'பெரிய பேனர்கள், எளிமையான பொத்தான்கள், பெரிய எழுத்துக்கள் மற்றும் எளிய வழிசெலுத்தலைக் காட்டுகிறது.',
      save_btn: 'அமைப்புகளைச் சேமி',
      saving: 'சேமிக்கப்படுகிறது...',
      tab_profile: 'சுயவிவரம்',
      tab_security: 'பாதுகாப்பு',
      tab_notifications: 'அறிவிப்புகள்',
      tab_users: 'பயனர் மேலாண்மை',
      personal_info: 'தனிப்பட்ட தகவல்',
      role: 'பங்கு',
      email_hint: 'மின்னஞ்சலை மாற்ற முடியாது.',
      change_password: 'கடவுச்சொல்லை மாற்று',
      current_password: 'தற்போதைய கடவுச்சொல்',
      new_password: 'புதிய கடவுச்சொல்',
      confirm_new_password: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      update_password: 'கடவுச்சொல்லைப் புதுப்பி',
      updating: 'புதுப்பிக்கப்படுகிறது...',
      session_info: 'அமர்வு தகவல்',
      logged_in_as: 'உள்நுழைந்துள்ளவர்',
      session_expires: 'அமர்வு காலாவதி',
      session_expiry_value: 'உள்நுழைந்ததிலிருந்து 24 மணிநேரம்',
      notification_preferences: 'அறிவிப்பு விருப்பங்கள்',
      pref_critical: 'முக்கிய நோய் எச்சரிக்கைகள்',
      pref_critical_desc: 'முக்கிய நோய் பரவல்கள் குறித்த உடனடி அறிவிப்புகளைப் பெறுங்கள்',
      pref_visitors: 'புதிய பார்வையாளர் கோரிக்கைகள்',
      pref_visitors_desc: 'பார்வையாளர்கள் பண்ணை அணுகலைக் கோரும்போது அறிவிப்பைப் பெறுங்கள்',
      pref_reports: 'அறிக்கை உருவாக்கம் முடிந்தது',
      pref_reports_desc: 'திட்டமிடப்பட்ட அறிக்கைகள் பதிவிறக்கம் செய்யத் தயாராக இருக்கும்போது அறிவிக்கவும்',
      pref_digest: 'வாராந்திர சுருக்கம்',
      pref_digest_desc: 'பண்ணை உயிரியல் பாதுகாப்பு நிலையின் வாராந்திர சுருக்கம்',
      save_preferences: 'விருப்பங்களைச் சேமி',
      user_management: 'பயனர் மேலாண்மை',
      table_user: 'பயனர்',
      table_email: 'மின்னஞ்சல்',
      table_role: 'பங்கு',
      table_joined: 'இணைந்த நாள்'
    }
  },
  hi: {
    common: {
      save: 'बदलाव सहेजें',
      cancel: 'रद्द करें',
      add: 'जोड़ें',
      edit: 'संपादित करें',
      delete: 'हटाएं',
      actions: 'कार्रवाई',
      status: 'स्थिति',
      loading: 'लोड हो रहा है...',
      success: 'सफलता',
      error: 'त्रुटि',
      active: 'सक्रिय',
      resolved: 'सुलझाया गया',
      submit: 'जमा करें'
    },
    nav: {
      dashboard: 'डैशबोर्ड',
      farms: 'फार्म',
      visitors: 'आगंतुक',
      biosecurity: 'जैव सुरक्षा',
      alerts: 'अलर्ट',
      reports: 'रिपोर्ट',
      settings: 'सेटिंग्स',
      disease_scanner: 'रोग स्कैनर',
      logout: 'लॉगआउट',
      light_mode: 'दिन मोड',
      dark_mode: 'रात मोड',
      portal_title: 'फार्मगार्ड',
      portal_subtitle: 'जैव सुरक्षा पोर्टल'
    },
    auth: {
      welcome_back: 'स्वागत है',
      signin_subtitle: 'अपने फार्मगार्ड खाते में साइन इन करें',
      create_account: 'अपना खाता बनाएं',
      signup_subtitle: 'अपनी फार्म जैव सुरक्षा का प्रबंधन शुरू करें',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      confirm_password: 'पासवर्ड की पुष्टि करें',
      repeat_password: 'पासवर्ड दोबारा दर्ज करें',
      full_name: 'पूरा नाम',
      full_name_placeholder: 'जॉन स्मिथ',
      email_placeholder: 'you@farm.com',
      password_placeholder: '••••••••',
      password_hint: 'कम से कम 6 अक्षर',
      signin_btn: 'साइन इन करें',
      signing_in: 'साइन इन हो रहा है...',
      signup_btn: 'खाता बनाएं',
      signing_up: 'खाता बनाया जा रहा है...',
      no_account: 'खाता नहीं है?',
      have_account: 'पहले से खाता है?',
      login_link: 'साइन इन करें',
      register_link: 'खाता बनाएं',
      welcome_toast: 'वापसी पर स्वागत है!',
      register_toast: 'खाता सफलतापूर्वक बन गया! फार्मगार्ड में आपका स्वागत है।',
      error_login: 'लॉगिन विफल रहा। कृपया पुन: प्रयास करें।',
      error_register: 'पंजीकरण विफल रहा।',
      validate_name: 'पूरा नाम आवश्यक है',
      validate_email: 'ईमेल आवश्यक है',
      validate_email_format: 'अमान्य ईमेल प्रारूप',
      validate_password: 'पासवर्ड आवश्यक है',
      validate_password_len: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      validate_confirm: 'पासवर्ड मेल नहीं खाते'
    },
    dashboard: {
      title: 'डैशबोर्ड',
      greeting_morning: 'शुभ प्रभात',
      greeting_afternoon: 'नमस्कार',
      greeting_evening: 'शुभ संध्या',
      overview_subtitle: 'यह आपके फार्म का अवलोकन है।',
      view_farms: 'फार्म देखें',
      new_alert: 'नया अलर्ट',
      total_farms: 'कुल फार्म',
      healthy_count: 'स्वस्थ',
      active_alerts: 'सक्रिय अलर्ट',
      critical_count: 'गंभीर',
      pending_visitors: 'लंबित आगंतुक',
      awaiting_approval: 'अनुमोदन की प्रतीक्षा',
      avg_compliance: 'औसत अनुपालन',
      biosecurity_score: 'जैव सुरक्षा स्कोर',
      activity_trend: '7-दिवसीय गतिविधि रुझान',
      live_indicator: 'लाइव',
      visitors: 'आगंतुक',
      alerts: 'अलर्ट',
      no_alerts: 'कोई सक्रिय अलर्ट नहीं है',
      no_visitors: 'कोई लंबित आगंतुक नहीं है'
    },
    scanner: {
      title: 'एआई रोग स्कैनर',
      subtitle: 'बीमारियों का जल्दी पता लगाने के लिए उन्नत न्यूरल विज़न एल्गोरिदम का उपयोग करके अपने फार्म के जानवरों की तस्वीरों का विश्लेषण करें।',
      banner_title: 'एआई रोग पहचान और निगरानी',
      banner_desc: 'वास्तविक समय में स्वचालित रोगज़नक़ आकलन चलाने के लिए बीमार जानवरों या फसल की विसंगतियों की स्पष्ट क्लोज़-अप तस्वीरें लें या अपलोड करें।',
      source_selection: 'इनपुट स्रोत चुनें',
      camera_mode: 'रियल-टाइम कैमरा',
      upload_mode: 'छवि अपलोड',
      allow_camera: 'स्कैन करने के लिए कृपया कैमरा अनुमति दें।',
      camera_error: 'कैमरा एक्सेस नहीं किया जा सका। कृपया फ़ाइल अपलोड का उपयोग करें।',
      start_camera: 'कैमरा फीड शुरू करें',
      stop_camera: 'कैमरा फीड बंद करें',
      capture_btn: 'तस्वीर लें और विश्लेषण करें',
      upload_prompt: 'अपने फार्म के जानवर की छवि को यहाँ खींचकर छोड़ें, या',
      browse_files: 'फ़ाइलें ब्राउज़ करें',
      file_selected: 'छवि सफलतापूर्वक लोड हो गई।',
      scan_now: 'छवि का विश्लेषण करें',
      scanning_progress: 'एआई विश्लेषण चल रहा है...',
      scan_log_1: 'शारीरिक विसंगतियों का पता लगाया जा रहा है...',
      scan_log_2: 'घाव के पैटर्न का विश्लेषण किया जा रहा है...',
      scan_log_3: 'शरीर के तापमान के संकेतों की जाँच हो रही है...',
      scan_log_4: 'वायरस रोगजनकों का मिलान किया जा रहा है...',
      diagnostic_report: 'एआई नैदानिक रिपोर्ट',
      confidence: 'आत्मविश्वास दर',
      pathogen: 'कंडारिया रोग (बीमारी)',
      severity: 'गंभीरता का स्तर',
      symptoms: 'पाए गए लक्षण',
      recommendations: 'क्वारंटाइन प्रक्रियाएं',
      action_required: 'आवश्यक कार्रवाई',
      outbreak_persist: 'रोग अलर्ट दर्ज करें',
      outbreak_submitting: 'अलर्ट दर्ज हो रहा है...',
      select_farm: 'प्रभावित फार्म चुनें',
      affected_count: 'प्रभावित पशुओं की संख्या',
      log_success: 'रोग अलर्ट सफलतापूर्वक दर्ज किया गया और डेटाबेस में सहेजा गया!',
      log_error: 'रोग अलर्ट सहेजने में विफल। कृपया पुन: प्रयास करें।',
      alert_title: 'एआई निदान: {disease}',
      alert_description: 'एआई रोग स्कैन ने {confidence}% आत्मविश्वास के साथ {disease} की पहचान की है। तत्काल निरीक्षण की सिफारिश की जाती है।',
      severity_critical: 'अत्यंत गंभीर',
      severity_high: 'उच्च',
      severity_medium: 'मध्यम',
      severity_low: 'निम्न',
      no_farms_error: 'रोग प्रकोप अलर्ट जमा करने से पहले आपको एक फार्म बनाना होगा।'
    },
    farms: {
      title: 'फार्म प्रबंधन',
      managed_count: '{count} फार्म प्रबंधित',
      add_farm: 'फार्म जोड़ें',
      search_placeholder: 'फार्म खोजें...',
      all_types: 'सभी प्रकार',
      all_status: 'सभी स्थितियां',
      no_farms_title: 'कोई फार्म नहीं मिला',
      no_farms_desc: 'शुरू करने के लिए अपना पहला फार्म जोड़ें।',
      banner_title: 'मेरी कृषि भूमि',
      banner_desc: 'अपनी कृषि भूमि, जैव सुरक्षा स्थिति और अलर्ट ट्रैकिंग को आसानी से प्रबंधित करें।',
      farm_name: 'फार्म का नाम *',
      farm_type: 'फार्म का प्रकार *',
      capacity: 'क्षमता *',
      location: 'स्थान *',
      description: 'विवरण',
      adding: 'जोड़ा जा रहा है...',
      saving: 'सहेजा जा रहा है...',
      save_changes: 'बदलाव सहेजें',
      cancel: 'रद्द करें',
      add_new_title: 'नया फार्म जोड़ें',
      edit_title: 'फार्म संपादित करें',
      delete_title: 'फार्म हटाएं',
      delete_msg: 'क्या आप वाकई "{name}" फार्म को हटाना चाहते हैं? इससे सभी संबंधित डेटा हटा दिया जाएगा।',
      delete_btn: 'फार्म हटाएं',
      type_pig: '🐷 सूअर फार्म',
      type_poultry: '🐔 मुर्गी पालन फार्म',
      type_mixed: '🏡 मिश्रित फार्म',
      view_details: 'विवरण देखें →'
    },
    visitors: {
      title: 'आगंतुक लॉग',
      banner_title: 'फार्म आगंतुक लॉग',
      banner_desc: 'सख्त जैव सुरक्षा प्रोटोकॉल बनाए रखने के लिए अपने फार्म में आने वाले सभी आगंतुकों पर नज़र रखें।',
      add_visitor: 'आगंतुक दर्ज करें',
      search_placeholder: 'आगंतुक खोजें...',
      all_farms: 'सभी फार्म',
      all_statuses: 'सभी स्थितियां',
      no_visitors_title: 'कोई आगंतुक लॉग नहीं मिला',
      no_visitors_desc: 'प्रवेश अनुपालन को ट्रैक करने के लिए एक आगंतुक लॉग करें।',
      log_visitor_title: 'फार्म आगंतुक लॉग करें',
      edit_visitor_title: 'आगंतुक लॉग संपादित करें',
      visitor_name: 'आगंतुक का नाम *',
      farm: 'लक्षित फार्म *',
      purpose: 'यात्रा का उद्देश्य *',
      contact: 'संपर्क नंबर *',
      company: 'कंपनी / संगठन *',
      vehicle: 'वाहन संख्या *',
      temp_check: 'तापमान जांच उत्तीर्ण (°C) *',
      disinfection: 'पूर्ण कीटाणुशोधन पूरा हुआ *',
      ppe_worn: 'पीपीई और जूते पहने गए *',
      risk_score: 'जोखिम मूल्यांकन स्कोर',
      high_risk_warning: '⚠️ उच्च जैव सुरक्षा जोखिम! प्रवेश से पहले उचित कीटाणुशोधन सुनिश्चित करें।',
      approve_btn: 'प्रवेश स्वीकृत करें',
      reject_btn: 'प्रवेश अस्वीकृत करें',
      submitting: 'जमा किया जा रहा है...',
      allowed: 'स्वीकृत',
      denied: 'अस्वीकृत',
      pending: 'लंबित',
      status_approved: 'स्वीकृत',
      status_denied: 'अस्वीकृत',
      status_pending: 'लंबित'
    },
    alerts_page: {
      title: 'वास्तविक समय अलर्ट',
      banner_title: 'जैव सुरक्षा चेतावनी और खतरे',
      banner_desc: 'अपने क्षेत्र के पास सक्रिय बीमारी फैलने, तापमान सीमा और अनुपालन उल्लंघन के बारे में तुरंत अलर्ट प्राप्त करें।',
      create_alert: 'नया अलर्ट बनाएं',
      search_placeholder: 'अलर्ट खोजें...',
      all_types: 'सभी प्रकार',
      all_severities: 'सभी गंभीरता स्तर',
      no_alerts_title: 'कोई अलर्ट नहीं मिला',
      no_alerts_desc: 'आपके सिस्टम में कोई सक्रिय खतरा अलर्ट नहीं है।',
      create_alert_title: 'खतरा अलर्ट बनाएं',
      alert_title_label: 'अलर्ट शीर्षक *',
      alert_type: 'अलर्ट प्रकार *',
      severity: 'गंभीरता *',
      affected_farm: 'प्रभावित फार्म *',
      description: 'विस्तृत विवरण *',
      submitting: 'दर्ज किया जा रहा है...',
      file_alert_btn: 'खतरा अलर्ट दर्ज करें',
      type_outbreak: 'बीमारी का प्रकोप',
      type_temp: 'तापमान सीमा उल्लंघन',
      type_biosecurity: 'जैव सुरक्षा उल्लंघन',
      type_other: 'अन्य खतरा',
      sev_critical: 'अत्यंत गंभीर',
      sev_high: 'उच्च',
      sev_medium: 'मध्यम',
      sev_low: 'निम्न',
      resolve_btn: 'अलर्ट सुलझाएं',
      delete_btn: 'अलर्ट हटाएं',
      delete_title: 'अलर्ट हटाएं',
      delete_msg: 'क्या आप वाकई इस अलर्ट को हटाना चाहते हैं?'
    },
    biosecurity: {
      title: 'जैव सुरक्षा नियम',
      banner_title: 'जैव सुरक्षा नियम सत्यापन',
      banner_desc: 'अपने फार्म के जैव सुरक्षा नियमों का ऑडिट करें और वास्तविक समय में अनुपालन को ट्रैक करें।',
      score_card: 'कुल अनुपालन स्कोर',
      score_desc: 'आगंतुक जांच, कीटाणुशोधन ऑडिट और सक्रिय प्रकोपों के आधार पर गणना की जाती है।',
      checklist_title: 'मुख्य अनुपालन सूची',
      check_disinfection: 'दैनिक वाहन कीटाणुशोधन छिड़काव',
      check_ppe: 'किसान/कर्मचारी सुरक्षा गियर सत्यापन',
      check_boundary: 'सुरक्षित बाड़ लगाना और सीमा नियंत्रण',
      check_waste: 'उचित मृत पशु निपटान गड्ढा',
      check_feed: 'स्वच्छ चारा और पानी का क्लोरीनीकरण',
      risk_analysis: 'वास्तविक समय जोखिम विश्लेषण',
      risk_msg: 'सभी प्रणालियां ठीक हैं। जोखिम अभी कम है।',
      risk_high_msg: 'चेतावनी: लंबित आगंतुक मूल्यांकन और क्षेत्रीय खतरों के कारण जोखिम बढ़ गया है।',
      run_audit: 'ऑडिट करें'
    },
    reports: {
      title: 'अनुपालन रिपोर्ट',
      banner_title: 'विश्लेषण और अनुपालन रिपोर्ट',
      banner_desc: 'जैव सुरक्षा लॉग निर्यात करें और अपनी कृषि भूमि के ऐतिहासिक रुझानों का विश्लेषण करें।',
      total_visitors: 'कुल दर्ज आगंतुक',
      total_alerts: 'सक्रिय खतरा अलर्ट',
      avg_score: 'औसत जैव सुरक्षा स्कोर',
      recent_activity: 'हाल की गतिविधियां',
      export_pdf: 'PDF निर्यात करें',
      export_csv: 'CSV निर्यात करें',
      filter_date: 'तारीख की सीमा',
      analytics_title: 'रिपोर्ट और विश्लेषण',
      generated_at: 'उत्पन्न: {date}',
      print_report: 'रिपोर्ट प्रिंट करें',
      compliance_report: 'अनुपालन रिपोर्ट',
      visitor_analytics: 'आगंतुक विश्लेषण',
      disease_incidents: 'रोग घटनाएं',
      all_farms: 'सभी फार्म',
      generate: 'बनाएं',
      click_generate: 'रिपोर्ट लोड करने के लिए "बनाएं" पर क्लिक करें',
      overall_biosecurity_score: 'कुल जैव सुरक्षा स्कोर',
      farms_fully_compliant: 'पूर्णतः अनुपालन फार्म',
      farms_need_attention: 'ध्यान देने योग्य फार्म',
      farm_compliance_rates: 'फार्म अनुपालन दरें',
      farm_by_farm_breakdown: 'फार्म-दर-फार्म विवरण',
      visitor_status_distribution: 'आगंतुक स्थिति वितरण',
      top_visit_purposes: 'शीर्ष यात्रा के उद्देश्य',
      visits_by_farm: 'फार्म द्वारा यात्राएं',
      alert_severity_distribution: 'अलर्ट गंभीरता वितरण',
      incidents_by_farm: 'फार्म द्वारा घटनाएं',
      recent_incidents: 'हाल की घटनाएं',
      total_incidents: 'कुल घटनाएं',
      critical_alerts: 'गंभीर अलर्ट',
      active_alerts_count: 'सक्रिय अलर्ट',
      animals_affected: 'प्रभावित जानवर',
      table_farm: 'फार्म',
      table_type: 'प्रकार',
      table_checks: 'किए गए चेक',
      table_compliance: 'अनुपालन',
      table_status: 'स्थिति',
      table_title: 'शीर्षक',
      table_severity: 'गंभीरता',
      table_affected: 'प्रभावित',
      table_date: 'तारीख'
    },
    settings_page: {
      title: 'सिस्टम सेटिंग्स',
      banner_title: 'उपयोगकर्ता प्रोफ़ाइल और प्राथमिकताएं',
      banner_desc: 'अपने क्रेडेंशियल, डार्क मोड, भाषा सेटिंग्स और किसान मोड को कॉन्फ़िगर करें।',
      profile_info: 'प्रोफ़ाइल जानकारी',
      name: 'पूरा नाम',
      email: 'ईमेल पता',
      phone: 'फ़ोन नंबर',
      avatar: 'प्रोफ़ाइल तस्वीर',
      upload_avatar: 'प्रोफ़ाइल चित्र बदलें',
      language: 'भाषा चयन',
      theme: 'थीम मोड',
      farmer_mode: 'किसान सरल मोड',
      farmer_mode_desc: 'बड़े बैनर, सरल बटन, बड़े अक्षर और आसान नेविगेशन दिखाता है।',
      save_btn: 'सेटिंग्स सहेजें',
      saving: 'सहेजा जा रहा है...',
      tab_profile: 'प्रोफ़ाइल',
      tab_security: 'सुरक्षा',
      tab_notifications: 'अधिसूचनाएं',
      tab_users: 'उपयोगकर्ता प्रबंधन',
      personal_info: 'व्यक्तिगत जानकारी',
      role: 'भूमिका',
      email_hint: 'ईमेल बदला नहीं जा सकता।',
      change_password: 'पासवर्ड बदलें',
      current_password: 'वर्तमान पासवर्ड',
      new_password: 'नया पासवर्ड',
      confirm_new_password: 'नए पासवर्ड की पुष्टि करें',
      update_password: 'पासवर्ड अपडेट करें',
      updating: 'अपडेट किया जा रहा है...',
      session_info: 'सत्र की जानकारी',
      logged_in_as: 'इस रूप में लॉग इन हैं',
      session_expires: 'सत्र समाप्त होगा',
      session_expiry_value: 'लॉगिन से 24 घंटे',
      notification_preferences: 'अधिसूचना प्राथमिकताएं',
      pref_critical: 'गंभीर बीमारी अलर्ट',
      pref_critical_desc: 'गंभीर बीमारी के प्रकोप के लिए तत्काल सूचनाएं प्राप्त करें',
      pref_visitors: 'नए आगंतुक अनुरोध',
      pref_visitors_desc: 'आगंतुकों द्वारा फार्म पहुंच का अनुरोध करने पर अधिसूचित हों',
      pref_reports: 'रिपोर्ट निर्माण पूर्ण',
      pref_reports_desc: 'निर्धारित रिपोर्ट डाउनलोड के लिए तैयार होने पर सूचित करें',
      pref_digest: 'साप्ताहिक सारांश',
      pref_digest_desc: 'फार्म जैव सुरक्षा स्थिति का साप्ताहिक सारांश',
      save_preferences: 'प्राथमिकताएं सहेजें',
      user_management: 'उपयोगकर्ता प्रबंधन',
      table_user: 'उपयोगकर्ता',
      table_email: 'ईमेल',
      table_role: 'भूमिका',
      table_joined: 'शामिल हुए'
    }
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const stored = localStorage.getItem('farm_lang');
      return stored && ['en', 'ta', 'hi'].includes(stored) ? stored : 'en';
    } catch {
      return 'en';
    }
  });

  const changeLanguage = useCallback((lang) => {
    if (['en', 'ta', 'hi'].includes(lang)) {
      setLanguageState(lang);
      try {
        localStorage.setItem('farm_lang', lang);
      } catch (err) {
        console.error('Failed to save language setting to localStorage:', err);
      }
    }
  }, []);

  const t = useCallback((path, replacements = {}) => {
    const parts = path.split('.');
    let current = translations[language];
    
    for (const part of parts) {
      if (current === undefined || current === null) {
        return path;
      }
      current = current[part];
    }
    
    if (typeof current !== 'string') {
      return path;
    }

    let result = current;
    for (const [key, value] of Object.entries(replacements)) {
      result = result.replace(new RegExp(`{${key}}`, 'g'), String(value));
    }
    
    return result;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
